name: Cypress Report
description: Creates Cypress Report

inputs:
  cache-path:
    description: 'path of the cypress cache'
    default: ".cache/Cypress"

  retention:
    description: "how many days should the report be kept in Github"
    default: "2"

runs:
  using: composite
  steps:
  
    - name: Get Repository
      uses: actions/checkout@v3

    - name: Extract branch name
      shell: bash
      run: echo "branch=${{ github.head_ref || github.ref_name }}" >> $GITHUB_OUTPUT
      id: extract_branch      

    - name: Restore Node Modules Cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-v1-${{ steps.extract_branch.outputs.branch }}-${{ hashFiles('yarn.lock') }}
    
    - name: Restore Cypress Cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.cache-path }}
        key: cypress-v1-${{ steps.extract_branch.outputs.branch }}-${{ hashFiles('yarn.lock') }}

    - name: Restore Cache
      uses: actions/cache@v3
      with:
        path: /home/runner/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/.cache
        key: cache-v1-${{ steps.extract_branch.outputs.branch }}-${{ hashFiles('yarn.lock') }}

    - name: get-artifacts
      uses: actions/download-artifact@v3
      with:
        name: cypress
        path: ./cypress/

    - name: report-merger
      shell: bash
      run: |
        mkdir ./mochawesome-report
        npm run report:generate
        npm run report:merge

    - name: archive-report-artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: report-merged
        path: ./mochawesome-report
        retention-days: ${{ inputs.retention }}